default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: '0.0.0.0'
  port: 5432

development:
  <<: *default
  database: todd_development

test:
  <<: *default
  database: todd_test

production:
  <<: *default
  database: todd_production
